diff --git a/Dockerfile b/Dockerfile
index 92a072996..5fc3a19ab 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,6 +7,7 @@ RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone &
     apt-get update && \
     apt-get install -y \
         binutils-mips-linux-gnu \
+        gcc-mips-linux-gnu \
         build-essential \
         pkg-config \
         python3 \
