#ifndef R_RANDOMIZER_H
#define R_RANDOMIZER_H 1

#define MAX_AST_EVENTS 0x10

typedef enum {
    ROOT,
    KOKIRI_FOREST,
    DEKU_TREE_LOBBY,
    DEKU_TREE_BOSS,
    LOST_WOODS,
    LOST_WOODS_BRIDGE,
    SACRED_FOREST_MEADOW_ENTRY,
    GORON_CITY_WOODS_WARP,
    ZORA_RIVER,
    SACRED_FOREST_MEADOW,
    HYRULE_FIELD,
    LAKE_HYLIA,
    GERUDO_VALLEY,
    CASTLE_TOWN,
    KAKARIKO_VILLAGE,
    ZORA_RIVER_FRONT,
    LON_LON_RANCH,
    ZORAS_DOMAIN,
    WATER_TEMPLE_LOBBY,
    WATER_TEMPLE_BOSS,
    GERUDO_VALLEY_FAR_SIDE,
    GERUDO_FORTRESS,
    HAUNTED_WASTELAND,
    GERUDO_TRAINING_GROUND_LOBBY,
    DESERT_COLOSSUS,
    SPIRIT_TEMPLE_LOBBY,
    SPIRIT_TEMPLE_HANDS,
    SPIRIT_TEMPLE_BOSS,
    TEMPLE_OF_TIME,
    HYRULE_CASTLE_GROUNDS,
    GANONS_CASTLE_GROUNDS,
    BEYOND_DOOR_OF_TIME,
    GANONS_CASTLE_LOBBY,
    BOTTOM_OF_THE_WELL_LOBBY,
    GRAVEYARD,
    SHADOW_TEMPLE_LOBBY,
    SHADOW_TEMPLE_BOSS,
    DEATH_MOUNTAIN,
    GORON_CITY,
    DEATH_MOUNTAIN_CRATER_UPPER,
    DODONGOS_CAVERN_LOBBY,
    DODONGOS_CAVERN_BOSS,
    DEATH_MOUNTAIN_CRATER_LOWER,
    DEATH_MOUNTAIN_CRATER_CENTRAL,
    FIRE_TEMPLE_LOBBY,
    FIRE_TEMPLE_BIG_LAVA_ROOM,
    FIRE_TEMPLE_ELEVATOR_ROOM,
    FIRE_TEMPLE_MAZE_LOWER,
    FIRE_TEMPLE_NARROW_PATH,
    FIRE_TEMPLE_MAZE_UPPER,
    FIRE_TEMPLE_FLAME_MAZE,
    FIRE_TEMPLE_UPPER,
    FIRE_TEMPLE_BOSS,
    ZORAS_FOUNTAIN,
    JABU_JABUS_BELLY_LOBBY,
    JABU_JABUS_BELLY_BOSS,
    ICE_CAVERN_LOBBY,
    FOREST_TEMPLE_LOBBY,
    FOREST_TEMPLE_BLOCK_PUSH_ROOM,
    FOREST_TEMPLE_STRAIGHT_HALL,
    FOREST_TEMPLE_OUTSIDE_UPPER,
    FOREST_TEMPLE_BOW_REGION,
    FOREST_TEMPLE_FROZEN_EYE,
    FOREST_TEMPLE_BOSS,
    GANONS_CASTLE_TOWER,
    REGION_MAX
} RegionEnum;

typedef enum {
    ITEM,
    BOSS_KEY,
    COMPASS,
    MAP,
    SMALL_KEY,
    EVENT_ITEM,
    SONG,
    DUNGEON_REWARD,
} ItemType;

typedef enum {
    CHEST_LOCATION,
    EVENT_LOCATION,
} LocationType;

typedef enum TriState {
    TRUE,
    FALSE,
    NONE
} TriState;

void Randomizer_ThreadEntry(void* arg);

void Randomizer_PrintUsedMemory();

#endif