#ifndef TITLE_STATIC_H
#define TITLE_STATIC_H 1

#define gFileSelConnectorTex_WIDTH 24
#define gFileSelConnectorTex_HEIGHT 16
extern u64 gFileSelConnectorTex[];
#define gFileSelForestMedallionTex_WIDTH 16
#define gFileSelForestMedallionTex_HEIGHT 16
extern u64 gFileSelForestMedallionTex[];
#define gFileSelFireMedallionTex_WIDTH 16
#define gFileSelFireMedallionTex_HEIGHT 16
extern u64 gFileSelFireMedallionTex[];
#define gFileSelWaterMedallionTex_WIDTH 16
#define gFileSelWaterMedallionTex_HEIGHT 16
extern u64 gFileSelWaterMedallionTex[];
#define gFileSelSpiritMedallionTex_WIDTH 16
#define gFileSelSpiritMedallionTex_HEIGHT 16
extern u64 gFileSelSpiritMedallionTex[];
#define gFileSelShadowMedallionTex_WIDTH 16
#define gFileSelShadowMedallionTex_HEIGHT 16
extern u64 gFileSelShadowMedallionTex[];
#define gFileSelLightMedallionTex_WIDTH 16
#define gFileSelLightMedallionTex_HEIGHT 16
extern u64 gFileSelLightMedallionTex[];
#define gFileSelSurroundENGTex_WIDTH 48
#define gFileSelSurroundENGTex_HEIGHT 16
extern u64 gFileSelSurroundENGTex[];
#define gFileSelHeadsetENGTex_WIDTH 48
#define gFileSelHeadsetENGTex_HEIGHT 16
extern u64 gFileSelHeadsetENGTex[];
#define gFileSelHeadsetGERTex_WIDTH 48
#define gFileSelHeadsetGERTex_HEIGHT 16
extern u64 gFileSelHeadsetGERTex[];
#define gFileSelHeadsetFRATex_WIDTH 48
#define gFileSelHeadsetFRATex_HEIGHT 16
extern u64 gFileSelHeadsetFRATex[];
#define gFileSelMonoENGTex_WIDTH 48
#define gFileSelMonoENGTex_HEIGHT 16
extern u64 gFileSelMonoENGTex[];
#define gFileSelSOUNDENGTex_WIDTH 64
#define gFileSelSOUNDENGTex_HEIGHT 16
extern u64 gFileSelSOUNDENGTex[];
#define gFileSelSOUNDFRATex_WIDTH 64
#define gFileSelSOUNDFRATex_HEIGHT 16
extern u64 gFileSelSOUNDFRATex[];
#define gFileSelStereoENGTex_WIDTH 48
#define gFileSelStereoENGTex_HEIGHT 16
extern u64 gFileSelStereoENGTex[];
#define gFileSelStereoFRATex_WIDTH 48
#define gFileSelStereoFRATex_HEIGHT 16
extern u64 gFileSelStereoFRATex[];
#define gFileSelZTargetingENGTex_WIDTH 64
#define gFileSelZTargetingENGTex_HEIGHT 16
extern u64 gFileSelZTargetingENGTex[];
#define gFileSelZTargetingGERTex_WIDTH 144
#define gFileSelZTargetingGERTex_HEIGHT 16
extern u64 gFileSelZTargetingGERTex[];
#define gFileSelZTargetingFRATex_WIDTH 64
#define gFileSelZTargetingFRATex_HEIGHT 16
extern u64 gFileSelZTargetingFRATex[];
#define gFileSelSwitchENGTex_WIDTH 48
#define gFileSelSwitchENGTex_HEIGHT 16
extern u64 gFileSelSwitchENGTex[];
#define gFileSelSwitchGERTex_WIDTH 80
#define gFileSelSwitchGERTex_HEIGHT 16
extern u64 gFileSelSwitchGERTex[];
#define gFileSelSwitchFRATex_WIDTH 48
#define gFileSelSwitchFRATex_HEIGHT 16
extern u64 gFileSelSwitchFRATex[];
#define gFileSelHoldENGTex_WIDTH 48
#define gFileSelHoldENGTex_HEIGHT 16
extern u64 gFileSelHoldENGTex[];
#define gFileSelHoldGERTex_WIDTH 80
#define gFileSelHoldGERTex_HEIGHT 16
extern u64 gFileSelHoldGERTex[];
#define gFileSelHoldFRATex_WIDTH 48
#define gFileSelHoldFRATex_HEIGHT 16
extern u64 gFileSelHoldFRATex[];
#define gFileSelCheckBrightnessENGTex_WIDTH 128
#define gFileSelCheckBrightnessENGTex_HEIGHT 16
extern u64 gFileSelCheckBrightnessENGTex[];
#define gFileSelCheckBrightnessGERTex_WIDTH 128
#define gFileSelCheckBrightnessGERTex_HEIGHT 16
extern u64 gFileSelCheckBrightnessGERTex[];
#define gFileSelCheckBrightnessFRATex_WIDTH 128
#define gFileSelCheckBrightnessFRATex_HEIGHT 16
extern u64 gFileSelCheckBrightnessFRATex[];
#define gFileSelLanguageChoiceENGTex_WIDTH 48
#define gFileSelLanguageChoiceENGTex_HEIGHT 16
extern u64 gFileSelLanguageChoiceENGTex[];
#define gFileSelLanguageChoiceGERTex_WIDTH 48
#define gFileSelLanguageChoiceGERTex_HEIGHT 16
extern u64 gFileSelLanguageChoiceGERTex[];
#define gFileSelLanguageChoiceFRATex_WIDTH 48
#define gFileSelLanguageChoiceFRATex_HEIGHT 16
extern u64 gFileSelLanguageChoiceFRATex[];
#define gFileSelLanguageENGTex_WIDTH 64
#define gFileSelLanguageENGTex_HEIGHT 16
extern u64 gFileSelLanguageENGTex[];
#define gFileSelLanguageGERTex_WIDTH 64
#define gFileSelLanguageGERTex_HEIGHT 16
extern u64 gFileSelLanguageGERTex[];
#define gFileSelLanguageFRATex_WIDTH 64
#define gFileSelLanguageFRATex_HEIGHT 16
extern u64 gFileSelLanguageFRATex[];
#define gFileSelWindow1Tex_WIDTH 64
#define gFileSelWindow1Tex_HEIGHT 32
extern u64 gFileSelWindow1Tex[];
#define gFileSelWindow2Tex_WIDTH 64
#define gFileSelWindow2Tex_HEIGHT 32
extern u64 gFileSelWindow2Tex[];
#define gFileSelWindow3Tex_WIDTH 64
#define gFileSelWindow3Tex_HEIGHT 32
extern u64 gFileSelWindow3Tex[];
#define gFileSelWindow4Tex_WIDTH 48
#define gFileSelWindow4Tex_HEIGHT 32
extern u64 gFileSelWindow4Tex[];
#define gFileSelWindow5Tex_WIDTH 64
#define gFileSelWindow5Tex_HEIGHT 32
extern u64 gFileSelWindow5Tex[];
#define gFileSelWindow6Tex_WIDTH 64
#define gFileSelWindow6Tex_HEIGHT 32
extern u64 gFileSelWindow6Tex[];
#define gFileSelWindow7Tex_WIDTH 64
#define gFileSelWindow7Tex_HEIGHT 32
extern u64 gFileSelWindow7Tex[];
#define gFileSelWindow8Tex_WIDTH 48
#define gFileSelWindow8Tex_HEIGHT 32
extern u64 gFileSelWindow8Tex[];
#define gFileSelWindow9Tex_WIDTH 64
#define gFileSelWindow9Tex_HEIGHT 32
extern u64 gFileSelWindow9Tex[];
#define gFileSelWindow10Tex_WIDTH 64
#define gFileSelWindow10Tex_HEIGHT 32
extern u64 gFileSelWindow10Tex[];
#define gFileSelWindow11Tex_WIDTH 64
#define gFileSelWindow11Tex_HEIGHT 32
extern u64 gFileSelWindow11Tex[];
#define gFileSelWindow12Tex_WIDTH 48
#define gFileSelWindow12Tex_HEIGHT 32
extern u64 gFileSelWindow12Tex[];
#define gFileSelWindow13Tex_WIDTH 64
#define gFileSelWindow13Tex_HEIGHT 32
extern u64 gFileSelWindow13Tex[];
#define gFileSelWindow14Tex_WIDTH 64
#define gFileSelWindow14Tex_HEIGHT 32
extern u64 gFileSelWindow14Tex[];
#define gFileSelWindow15Tex_WIDTH 64
#define gFileSelWindow15Tex_HEIGHT 32
extern u64 gFileSelWindow15Tex[];
#define gFileSelWindow16Tex_WIDTH 48
#define gFileSelWindow16Tex_HEIGHT 32
extern u64 gFileSelWindow16Tex[];
#define gFileSelWindow17Tex_WIDTH 64
#define gFileSelWindow17Tex_HEIGHT 32
extern u64 gFileSelWindow17Tex[];
#define gFileSelWindow18Tex_WIDTH 64
#define gFileSelWindow18Tex_HEIGHT 32
extern u64 gFileSelWindow18Tex[];
#define gFileSelWindow19Tex_WIDTH 64
#define gFileSelWindow19Tex_HEIGHT 32
extern u64 gFileSelWindow19Tex[];
#define gFileSelWindow20Tex_WIDTH 48
#define gFileSelWindow20Tex_HEIGHT 32
extern u64 gFileSelWindow20Tex[];
#define gFileSelKanjiButtonTex_WIDTH 28
#define gFileSelKanjiButtonTex_HEIGHT 16
extern u64 gFileSelKanjiButtonTex[];
#define gFileSelHiraganaButtonTex_WIDTH 44
#define gFileSelHiraganaButtonTex_HEIGHT 16
extern u64 gFileSelHiraganaButtonTex[];
#define gFileSelKatakanaButtonTex_WIDTH 44
#define gFileSelKatakanaButtonTex_HEIGHT 16
extern u64 gFileSelKatakanaButtonTex[];
#define gFileSelENDButtonENGTex_WIDTH 44
#define gFileSelENDButtonENGTex_HEIGHT 16
extern u64 gFileSelENDButtonENGTex[];
#define gFileSelENDButtonGERTex_WIDTH 44
#define gFileSelENDButtonGERTex_HEIGHT 16
extern u64 gFileSelENDButtonGERTex[];
#define gFileSelENDButtonFRATex_WIDTH 44
#define gFileSelENDButtonFRATex_HEIGHT 16
extern u64 gFileSelENDButtonFRATex[];
#define gFileSelBackspaceButtonTex_WIDTH 28
#define gFileSelBackspaceButtonTex_HEIGHT 16
extern u64 gFileSelBackspaceButtonTex[];
#define gFileSelNameBoxTex_WIDTH 108
#define gFileSelNameBoxTex_HEIGHT 16
extern u64 gFileSelNameBoxTex[];
#define gFileSelFileInfoBox1Tex_WIDTH 36
#define gFileSelFileInfoBox1Tex_HEIGHT 56
extern u64 gFileSelFileInfoBox1Tex[];
#define gFileSelFileInfoBox2Tex_WIDTH 36
#define gFileSelFileInfoBox2Tex_HEIGHT 56
extern u64 gFileSelFileInfoBox2Tex[];
#define gFileSelFileInfoBox3Tex_WIDTH 36
#define gFileSelFileInfoBox3Tex_HEIGHT 56
extern u64 gFileSelFileInfoBox3Tex[];
#define gFileSelFileInfoBox4Tex_WIDTH 36
#define gFileSelFileInfoBox4Tex_HEIGHT 56
extern u64 gFileSelFileInfoBox4Tex[];
#define gFileSelFileInfoBox5Tex_WIDTH 24
#define gFileSelFileInfoBox5Tex_HEIGHT 56
extern u64 gFileSelFileInfoBox5Tex[];
#define gFileSelDISKButtonTex_WIDTH 44
#define gFileSelDISKButtonTex_HEIGHT 16
extern u64 gFileSelDISKButtonTex[];
#define gFileSelOptionsDividerTex_WIDTH 256
#define gFileSelOptionsDividerTex_HEIGHT 2
extern u64 gFileSelOptionsDividerTex[];
#define gFileSelBrightnessCheckTex_WIDTH 96
#define gFileSelBrightnessCheckTex_HEIGHT 16
extern u64 gFileSelBrightnessCheckTex[];
#define gFileSelBigButtonHighlightTex_WIDTH 72
#define gFileSelBigButtonHighlightTex_HEIGHT 24
extern u64 gFileSelBigButtonHighlightTex[];
#define gFileSelCharHighlightTex_WIDTH 24
#define gFileSelCharHighlightTex_HEIGHT 24
extern u64 gFileSelCharHighlightTex[];
#define gFileSelMediumButtonHighlightTex_WIDTH 56
#define gFileSelMediumButtonHighlightTex_HEIGHT 24
extern u64 gFileSelMediumButtonHighlightTex[];
#define gFileSelSmallButtonHighlightTex_WIDTH 40
#define gFileSelSmallButtonHighlightTex_HEIGHT 24
extern u64 gFileSelSmallButtonHighlightTex[];
#define gFileSelKokiriEmeraldTex_WIDTH 16
#define gFileSelKokiriEmeraldTex_HEIGHT 16
extern u64 gFileSelKokiriEmeraldTex[];
#define gFileSelGoronRubyTex_WIDTH 16
#define gFileSelGoronRubyTex_HEIGHT 16
extern u64 gFileSelGoronRubyTex[];
#define gFileSelZoraSapphireTex_WIDTH 16
#define gFileSelZoraSapphireTex_HEIGHT 16
extern u64 gFileSelZoraSapphireTex[];
#define gFileSelNoFileToCopyENGTex_WIDTH 128
#define gFileSelNoFileToCopyENGTex_HEIGHT 16
extern u64 gFileSelNoFileToCopyENGTex[];
#define gFileSelNoFileToEraseENGTex_WIDTH 128
#define gFileSelNoFileToEraseENGTex_HEIGHT 16
extern u64 gFileSelNoFileToEraseENGTex[];
#define gFileSelNoEmptyFileENGTex_WIDTH 128
#define gFileSelNoEmptyFileENGTex_HEIGHT 16
extern u64 gFileSelNoEmptyFileENGTex[];
#define gFileSelFileEmptyENGTex_WIDTH 128
#define gFileSelFileEmptyENGTex_HEIGHT 16
extern u64 gFileSelFileEmptyENGTex[];
#define gFileSelFileInUseENGTex_WIDTH 128
#define gFileSelFileInUseENGTex_HEIGHT 16
extern u64 gFileSelFileInUseENGTex[];
#define gFileSelCopyWhichFileENGTex_WIDTH 128
#define gFileSelCopyWhichFileENGTex_HEIGHT 16
extern u64 gFileSelCopyWhichFileENGTex[];
#define gFileSelCopyToWhichFileENGTex_WIDTH 128
#define gFileSelCopyToWhichFileENGTex_HEIGHT 16
extern u64 gFileSelCopyToWhichFileENGTex[];
#define gFileSelAreYouSureENGTex_WIDTH 128
#define gFileSelAreYouSureENGTex_HEIGHT 16
extern u64 gFileSelAreYouSureENGTex[];
#define gFileSelFileCopiedENGTex_WIDTH 128
#define gFileSelFileCopiedENGTex_HEIGHT 16
extern u64 gFileSelFileCopiedENGTex[];
#define gFileSelPleaseSelectAFileENGTex_WIDTH 128
#define gFileSelPleaseSelectAFileENGTex_HEIGHT 16
extern u64 gFileSelPleaseSelectAFileENGTex[];
#define gFileSelOpenThisFileENGTex_WIDTH 128
#define gFileSelOpenThisFileENGTex_HEIGHT 16
extern u64 gFileSelOpenThisFileENGTex[];
#define gFileSelEraseWhichFileENGTex_WIDTH 128
#define gFileSelEraseWhichFileENGTex_HEIGHT 16
extern u64 gFileSelEraseWhichFileENGTex[];
#define gFileSelAreYouSure2ENGTex_WIDTH 128
#define gFileSelAreYouSure2ENGTex_HEIGHT 16
extern u64 gFileSelAreYouSure2ENGTex[];
#define gFileSelFileErasedENGTex_WIDTH 128
#define gFileSelFileErasedENGTex_HEIGHT 16
extern u64 gFileSelFileErasedENGTex[];
#define gFileSelOptionsENGTex_WIDTH 128
#define gFileSelOptionsENGTex_HEIGHT 16
extern u64 gFileSelOptionsENGTex[];
#define gFileSelNameENGTex_WIDTH 56
#define gFileSelNameENGTex_HEIGHT 16
extern u64 gFileSelNameENGTex[];
#define gFileSelControlsENGTex_WIDTH 144
#define gFileSelControlsENGTex_HEIGHT 16
extern u64 gFileSelControlsENGTex[];
#define gFileSelCopyButtonENGTex_WIDTH 64
#define gFileSelCopyButtonENGTex_HEIGHT 16
extern u64 gFileSelCopyButtonENGTex[];
#define gFileSelFile1ButtonENGTex_WIDTH 64
#define gFileSelFile1ButtonENGTex_HEIGHT 16
extern u64 gFileSelFile1ButtonENGTex[];
#define gFileSelFile2ButtonENGTex_WIDTH 64
#define gFileSelFile2ButtonENGTex_HEIGHT 16
extern u64 gFileSelFile2ButtonENGTex[];
#define gFileSelFile3ButtonENGTex_WIDTH 64
#define gFileSelFile3ButtonENGTex_HEIGHT 16
extern u64 gFileSelFile3ButtonENGTex[];
#define gFileSelYesButtonENGTex_WIDTH 64
#define gFileSelYesButtonENGTex_HEIGHT 16
extern u64 gFileSelYesButtonENGTex[];
#define gFileSelEraseButtonENGTex_WIDTH 64
#define gFileSelEraseButtonENGTex_HEIGHT 16
extern u64 gFileSelEraseButtonENGTex[];
#define gFileSelOptionsButtonENGTex_WIDTH 64
#define gFileSelOptionsButtonENGTex_HEIGHT 16
extern u64 gFileSelOptionsButtonENGTex[];
#define gFileSelOptionsButtonGERTex_WIDTH 64
#define gFileSelOptionsButtonGERTex_HEIGHT 16
extern u64 gFileSelOptionsButtonGERTex[];
#define gFileSelQuitButtonENGTex_WIDTH 64
#define gFileSelQuitButtonENGTex_HEIGHT 16
extern u64 gFileSelQuitButtonENGTex[];
#define gFileSelNoFileToCopyGERTex_WIDTH 128
#define gFileSelNoFileToCopyGERTex_HEIGHT 16
extern u64 gFileSelNoFileToCopyGERTex[];
#define gFileSelNoFileToEraseGERTex_WIDTH 128
#define gFileSelNoFileToEraseGERTex_HEIGHT 16
extern u64 gFileSelNoFileToEraseGERTex[];
#define gFileSelNoEmptyFileGERTex_WIDTH 128
#define gFileSelNoEmptyFileGERTex_HEIGHT 16
extern u64 gFileSelNoEmptyFileGERTex[];
#define gFileSelFileEmptyGERTex_WIDTH 128
#define gFileSelFileEmptyGERTex_HEIGHT 16
extern u64 gFileSelFileEmptyGERTex[];
#define gFileSelFileInUseGERTex_WIDTH 128
#define gFileSelFileInUseGERTex_HEIGHT 16
extern u64 gFileSelFileInUseGERTex[];
#define gFileSelCopyWhichFileGERTex_WIDTH 128
#define gFileSelCopyWhichFileGERTex_HEIGHT 16
extern u64 gFileSelCopyWhichFileGERTex[];
#define gFileSelCopyToWhichFileGERTex_WIDTH 128
#define gFileSelCopyToWhichFileGERTex_HEIGHT 16
extern u64 gFileSelCopyToWhichFileGERTex[];
#define gFileSelAreYouSureGERTex_WIDTH 128
#define gFileSelAreYouSureGERTex_HEIGHT 16
extern u64 gFileSelAreYouSureGERTex[];
#define gFileSelFileCopiedGERTex_WIDTH 128
#define gFileSelFileCopiedGERTex_HEIGHT 16
extern u64 gFileSelFileCopiedGERTex[];
#define gFileSelPleaseSelectAFileGERTex_WIDTH 128
#define gFileSelPleaseSelectAFileGERTex_HEIGHT 16
extern u64 gFileSelPleaseSelectAFileGERTex[];
#define gFileSelOpenThisFileGERTex_WIDTH 128
#define gFileSelOpenThisFileGERTex_HEIGHT 16
extern u64 gFileSelOpenThisFileGERTex[];
#define gFileSelEraseWhichFileGERTex_WIDTH 128
#define gFileSelEraseWhichFileGERTex_HEIGHT 16
extern u64 gFileSelEraseWhichFileGERTex[];
#define gFileSelAreYouSure2GERTex_WIDTH 128
#define gFileSelAreYouSure2GERTex_HEIGHT 16
extern u64 gFileSelAreYouSure2GERTex[];
#define gFileSelFileErasedGERTex_WIDTH 128
#define gFileSelFileErasedGERTex_HEIGHT 16
extern u64 gFileSelFileErasedGERTex[];
#define gFileSelOptionsGERTex_WIDTH 128
#define gFileSelOptionsGERTex_HEIGHT 16
extern u64 gFileSelOptionsGERTex[];
#define gFileSelNameGERTex_WIDTH 56
#define gFileSelNameGERTex_HEIGHT 16
extern u64 gFileSelNameGERTex[];
#define gFileSelControlsGERTex_WIDTH 144
#define gFileSelControlsGERTex_HEIGHT 16
extern u64 gFileSelControlsGERTex[];
#define gFileSelCopyButtonGERTex_WIDTH 64
#define gFileSelCopyButtonGERTex_HEIGHT 16
extern u64 gFileSelCopyButtonGERTex[];
#define gFileSelFile1ButtonGERTex_WIDTH 64
#define gFileSelFile1ButtonGERTex_HEIGHT 16
extern u64 gFileSelFile1ButtonGERTex[];
#define gFileSelFile2ButtonGERTex_WIDTH 64
#define gFileSelFile2ButtonGERTex_HEIGHT 16
extern u64 gFileSelFile2ButtonGERTex[];
#define gFileSelFile3ButtonGERTex_WIDTH 64
#define gFileSelFile3ButtonGERTex_HEIGHT 16
extern u64 gFileSelFile3ButtonGERTex[];
#define gFileSelYesButtonGERTex_WIDTH 64
#define gFileSelYesButtonGERTex_HEIGHT 16
extern u64 gFileSelYesButtonGERTex[];
#define gFileSelEraseButtonGERTex_WIDTH 64
#define gFileSelEraseButtonGERTex_HEIGHT 16
extern u64 gFileSelEraseButtonGERTex[];
#define gFileSelQuitButtonGERTex_WIDTH 64
#define gFileSelQuitButtonGERTex_HEIGHT 16
extern u64 gFileSelQuitButtonGERTex[];
#define gFileSelNoFileToCopyFRATex_WIDTH 128
#define gFileSelNoFileToCopyFRATex_HEIGHT 16
extern u64 gFileSelNoFileToCopyFRATex[];
#define gFileSelNoFileToEraseFRATex_WIDTH 128
#define gFileSelNoFileToEraseFRATex_HEIGHT 16
extern u64 gFileSelNoFileToEraseFRATex[];
#define gFileSelNoEmptyFileFRATex_WIDTH 128
#define gFileSelNoEmptyFileFRATex_HEIGHT 16
extern u64 gFileSelNoEmptyFileFRATex[];
#define gFileSelFileEmptyFRATex_WIDTH 128
#define gFileSelFileEmptyFRATex_HEIGHT 16
extern u64 gFileSelFileEmptyFRATex[];
#define gFileSelFileInUseFRATex_WIDTH 128
#define gFileSelFileInUseFRATex_HEIGHT 16
extern u64 gFileSelFileInUseFRATex[];
#define gFileSelCopyWhichFileFRATex_WIDTH 128
#define gFileSelCopyWhichFileFRATex_HEIGHT 16
extern u64 gFileSelCopyWhichFileFRATex[];
#define gFileSelCopyToWhichFileFRATex_WIDTH 128
#define gFileSelCopyToWhichFileFRATex_HEIGHT 16
extern u64 gFileSelCopyToWhichFileFRATex[];
#define gFileSelAreYouSureFRATex_WIDTH 128
#define gFileSelAreYouSureFRATex_HEIGHT 16
extern u64 gFileSelAreYouSureFRATex[];
#define gFileSelFileCopiedFRATex_WIDTH 128
#define gFileSelFileCopiedFRATex_HEIGHT 16
extern u64 gFileSelFileCopiedFRATex[];
#define gFileSelPleaseSelectAFileFRATex_WIDTH 128
#define gFileSelPleaseSelectAFileFRATex_HEIGHT 16
extern u64 gFileSelPleaseSelectAFileFRATex[];
#define gFileSelOpenThisFileFRATex_WIDTH 128
#define gFileSelOpenThisFileFRATex_HEIGHT 16
extern u64 gFileSelOpenThisFileFRATex[];
#define gFileSelEraseWhichFileFRATex_WIDTH 128
#define gFileSelEraseWhichFileFRATex_HEIGHT 16
extern u64 gFileSelEraseWhichFileFRATex[];
#define gFileSelAreYouSure2FRATex_WIDTH 128
#define gFileSelAreYouSure2FRATex_HEIGHT 16
extern u64 gFileSelAreYouSure2FRATex[];
#define gFileSelFileErasedFRATex_WIDTH 128
#define gFileSelFileErasedFRATex_HEIGHT 16
extern u64 gFileSelFileErasedFRATex[];
#define gFileSelNameFRATex_WIDTH 56
#define gFileSelNameFRATex_HEIGHT 16
extern u64 gFileSelNameFRATex[];
#define gFileSelControlsFRATex_WIDTH 144
#define gFileSelControlsFRATex_HEIGHT 16
extern u64 gFileSelControlsFRATex[];
#define gFileSelCopyButtonFRATex_WIDTH 64
#define gFileSelCopyButtonFRATex_HEIGHT 16
extern u64 gFileSelCopyButtonFRATex[];
#define gFileSelFile1ButtonFRATex_WIDTH 64
#define gFileSelFile1ButtonFRATex_HEIGHT 16
extern u64 gFileSelFile1ButtonFRATex[];
#define gFileSelFile2ButtonFRATex_WIDTH 64
#define gFileSelFile2ButtonFRATex_HEIGHT 16
extern u64 gFileSelFile2ButtonFRATex[];
#define gFileSelFile3ButtonFRATex_WIDTH 64
#define gFileSelFile3ButtonFRATex_HEIGHT 16
extern u64 gFileSelFile3ButtonFRATex[];
#define gFileSelYesButtonFRATex_WIDTH 64
#define gFileSelYesButtonFRATex_HEIGHT 16
extern u64 gFileSelYesButtonFRATex[];
#define gFileSelEraseButtonFRATex_WIDTH 64
#define gFileSelEraseButtonFRATex_HEIGHT 16
extern u64 gFileSelEraseButtonFRATex[];
#define gFileSelQuitButtonFRATex_WIDTH 64
#define gFileSelQuitButtonFRATex_HEIGHT 16
extern u64 gFileSelQuitButtonFRATex[];
#define gFileSelInitialLanguageChoiceENGTex_WIDTH 80
#define gFileSelInitialLanguageChoiceENGTex_HEIGHT 32
extern u64 gFileSelInitialLanguageChoiceENGTex[];
#define gFileSelInitialLanguageChoiceGERTex_WIDTH 80
#define gFileSelInitialLanguageChoiceGERTex_HEIGHT 32
extern u64 gFileSelInitialLanguageChoiceGERTex[];
#define gFileSelInitialLanguageChoiceFRATex_WIDTH 80
#define gFileSelInitialLanguageChoiceFRATex_HEIGHT 32
extern u64 gFileSelInitialLanguageChoiceFRATex[];
#define gFileSelSelectYourLanguageTex_WIDTH 160
#define gFileSelSelectYourLanguageTex_HEIGHT 60
extern u64 gFileSelSelectYourLanguageTex[];
extern u8 title_static_unaccounted_04C680[];
#define gFileSelInitialLanguageCursorTex_WIDTH 48
#define gFileSelInitialLanguageCursorTex_HEIGHT 48
extern u64 gFileSelInitialLanguageCursorTex[];
extern u64 gRandoControlsENGTex[];
extern u64 gRandoYesENGTex[];
extern u64 gRandoNoENGTex[];
extern u64 gRandoSettingsENGTex[];
extern u64 gRandoShuffleENGTex[];
extern u64 gRandoChestsENGTex[];
extern u64 gOptionQuicktextENGTex[];
extern u64 gOptionOnENGTex[];
extern u64 gOptionOffENGTex[];
extern Gfx gFileSelWindow1DL[];
extern Gfx gFileSelWindow2DL[];
extern Gfx gFileSelWindow3DL[];
#endif
